/**
 * Sycord Injector — extract-and-patch strategy
 *
 * Modern Electron loads resources/app.asar as an archive. It does NOT
 * prefer a sibling resources/app/ folder. So to inject, we:
 *   1. Back up app.asar
 *   2. Extract it into resources/app/
 *   3. Prepend a require() to Discord's main entry that loads our hook
 *   4. Delete app.asar so Electron loads the folder
 *
 * The hook patches BrowserWindow to:
 *   - swap in our preload (which chains Discord's original preload)
 *   - call webContents.executeJavaScript() with renderer.js after load,
 *     bypassing Discord's CSP
 *
 * IMPORTANT: We do NOT touch contextIsolation. Discord sets it to true and
 * its auth/session code depends on the isolated-world boundary. Forcing it
 * to false breaks login persistence (Discord logs you out on every launch).
 *
 * Uninject reverses steps 1-4.
 */

import { existsSync, mkdirSync, rmSync, readdirSync, statSync, readFileSync, writeFileSync, copyFileSync } from "fs";
import { join, resolve } from "path";
import { platform, env, exit, argv } from "process";
import { createRequire } from "module";

const require = createRequire(import.meta.url);
const asar    = require("@electron/asar");

const UNINJECT = argv.includes("--uninject");

// ── Locate the live Discord resources folder ─────────────────────────────────
function findDiscordResources() {
    if (platform === "win32") {
        const base = join(env.LOCALAPPDATA, "Discord");
        if (!existsSync(base)) throw new Error(`Discord not found: ${base}`);

        const dirs = readdirSync(base)
            .filter(d => /^app-\d+\.\d+\.\d+$/.test(d))
            .sort((a, b) => {
                const va = a.replace("app-", "").split(".").map(Number);
                const vb = b.replace("app-", "").split(".").map(Number);
                for (let i = 0; i < 3; i++) if (va[i] !== vb[i]) return vb[i] - va[i];
                return 0;
            });

        if (!dirs.length) throw new Error("No Discord app directory found");

        for (const d of dirs) {
            const res = join(base, d, "resources");
            if (!existsSync(res)) continue;

            const asarFile = join(res, "app.asar");
            const appPkg   = join(res, "app", "package.json");

            const hasAsarFile = existsSync(asarFile) && statSync(asarFile).isFile();
            const hasAppDir   = existsSync(appPkg);

            if (hasAsarFile || hasAppDir) {
                console.log(`ℹ  Using Discord install: ${d}`);
                return res;
            }
        }

        throw new Error(
            "Found Discord folders but none contain a complete install. " +
            "Launch Discord once so it finishes installing, then retry."
        );
    }

    if (platform === "darwin") {
        const base = "/Applications/Discord.app/Contents/Resources";
        if (existsSync(base)) return base;
        throw new Error(`Discord not found: ${base}`);
    }

    if (platform === "linux") {
        const candidates = [
            "/usr/lib/discord",
            "/opt/discord",
            `${env.HOME}/.local/share/discord`,
        ];
        for (const c of candidates) {
            const r = join(c, "resources");
            if (existsSync(r)) return r;
        }
        throw new Error("Discord resources not found. Check candidates in inject.mjs");
    }

    throw new Error(`Unsupported platform: ${platform}`);
}

// ── The hook file: dropped into resources/app/, required by Discord's entry ──
function makeHookCode(sycordDir) {
    const sycordDirStr = JSON.stringify(sycordDir);

    return `
// ── Sycord Hook ────────────────────────────────────────────────────────────
// Auto-generated by scripts/inject.mjs — DO NOT EDIT MANUALLY
// Sycord source: ${sycordDirStr}

"use strict";
const path   = require("path");
const fs     = require("fs");
const Module = require("module");
const { app } = require("electron");

const SYCORD_DIR    = ${sycordDirStr};
const RENDERER_PATH = path.join(SYCORD_DIR, "renderer.js");

// Intercept require("electron") so we can proxy BrowserWindow
const originalLoad = Module._load.bind(Module);

Module._load = function(request, parent, isMain) {
    if (request !== "electron") return originalLoad(request, parent, isMain);

    const electron = originalLoad("electron", parent, isMain);
    if (electron.__sycordPatched) return electron;

    const { BrowserWindow: OrigBW } = electron;

    const PatchedBW = new Proxy(OrigBW, {
        construct(target, args) {
            const opts     = args[0] || {};
            const webPrefs = Object.assign({}, opts.webPreferences || {});

            // Remember Discord's original preload so ours can chain it
            if (webPrefs.preload) {
                process.env.SYCORD_ORIGINAL_PRELOAD = webPrefs.preload;
            }

            // Swap in our preload. We do NOT touch contextIsolation —
            // Discord's auth/session handling depends on it being true.
            webPrefs.preload = path.join(SYCORD_DIR, "preload.js");

            args[0] = Object.assign({}, opts, { webPreferences: webPrefs });

            const win = new target(...args);

            // ── Deliver renderer bundle via executeJavaScript ───────────────
            // This bypasses Discord's CSP entirely because it's a privileged
            // Electron API, not a page-level <script> tag injection.
            try {
                win.webContents.on("did-finish-load", () => {
                    try {
                        const code = fs.readFileSync(RENDERER_PATH, "utf-8");
                        win.webContents.executeJavaScript(code, true)
                            .then(() => console.log("[Sycord] Renderer delivered to window ✅"))
                            .catch(e => console.error("[Sycord] executeJavaScript rejected:", e));
                    } catch (e) {
                        console.error("[Sycord] Failed to read/deliver renderer.js:", e);
                    }
                });
            } catch (e) {
                console.error("[Sycord] Failed to attach did-finish-load listener:", e);
            }

            return win;
        },
        get(target, prop) {
            if (prop === "prototype") return target.prototype;
            return typeof target[prop] === "function"
                ? target[prop].bind(target)
                : target[prop];
        }
    });

    return Object.assign(
        Object.create(Object.getPrototypeOf(electron)),
        electron,
        { BrowserWindow: PatchedBW, __sycordPatched: true }
    );
};

console.log("[Sycord] Hook active 🔥");

app.whenReady().then(() => {
    console.log("[Sycord] App ready — BrowserWindows will receive the renderer on load");
});
`;
}

// ── Main ─────────────────────────────────────────────────────────────────────
async function main() {
    let resourcesPath;
    try {
        resourcesPath = findDiscordResources();
    } catch (e) {
        console.error("❌ " + e.message);
        exit(1);
    }

    const appAsar    = join(resourcesPath, "app.asar");
    const appAsarBak = join(resourcesPath, "app.asar.backup");
    const appDir     = join(resourcesPath, "app");

    // ── Refuse to run if Discord is alive (Windows check) ───────────────────
    if (platform === "win32") {
        const { execSync } = await import("child_process");
        try {
            const out = execSync('tasklist /FI "IMAGENAME eq Discord.exe" /NH', { encoding: "utf-8" });
            if (/Discord\.exe/i.test(out)) {
                console.error("❌ Discord is still running. Quit it fully (tray icon → Quit) and retry.");
                exit(1);
            }
        } catch { /* tasklist failed — carry on */ }
    }

    // ── UNINJECT ────────────────────────────────────────────────────────────
    if (UNINJECT) {
        let didSomething = false;

        if (existsSync(appDir)) {
            const marker = join(appDir, "sycord-hook.js");
            if (existsSync(marker)) {
                rmSync(appDir, { recursive: true, force: true });
                console.log("✅ Removed extracted app/ folder");
                didSomething = true;
            } else {
                console.warn("⚠  resources/app/ exists but has no sycord-hook.js. Not removing.");
            }
        }

        if (existsSync(appAsarBak)) {
            if (existsSync(appAsar)) rmSync(appAsar, { force: true });
            copyFileSync(appAsarBak, appAsar);
            rmSync(appAsarBak, { force: true });
            console.log("✅ Restored app.asar from backup");
            didSomething = true;
        }

        if (!didSomething) console.log("ℹ  Nothing to uninject.");
        return;
    }

    // ── INJECT ──────────────────────────────────────────────────────────────

    if (existsSync(join(appDir, "sycord-hook.js")) && !existsSync(appAsar)) {
        console.log("ℹ  Already injected. Re-running to refresh hook.");
    }

    if (existsSync(appAsar)) {
        if (!statSync(appAsar).isFile()) {
            console.error("❌ app.asar is not a file. Discord install is in an odd state.");
            console.error("   Uninstall and reinstall Discord, then retry.");
            exit(1);
        }

        if (!existsSync(appAsarBak)) {
            console.log("… backing up app.asar");
            copyFileSync(appAsar, appAsarBak);
        }

        if (existsSync(appDir)) {
            console.log("… clearing old resources/app/");
            rmSync(appDir, { recursive: true, force: true });
        }

        console.log("… extracting app.asar → resources/app/ (this takes a few seconds)");
        try {
            asar.extractAll(appAsar, appDir);
        } catch (e) {
            console.error("❌ Extraction failed:", e.message);
            exit(1);
        }

        console.log("… removing app.asar (Electron will now load the folder)");
        rmSync(appAsar, { force: true });
    }

    if (!existsSync(appDir)) {
        console.error("❌ resources/app/ missing and no app.asar to extract from.");
        exit(1);
    }

    // ── Drop the hook ───────────────────────────────────────────────────────
    const sycordDist = resolve("dist");
    const preloadJs  = join(sycordDist, "preload.js");
    const rendererJs = join(sycordDist, "renderer.js");

    if (!existsSync(preloadJs)) {
        console.error("❌ dist/preload.js not found. Run 'npm run build' first.");
        exit(1);
    }
    if (!existsSync(rendererJs)) {
        console.error("❌ dist/renderer.js not found. Run 'npm run build' first.");
        exit(1);
    }

    writeFileSync(join(appDir, "sycord-hook.js"), makeHookCode(sycordDist));
    console.log("… wrote sycord-hook.js");

    // ── Find Discord's main entry and prepend our require ───────────────────
    const pkgPath = join(appDir, "package.json");
    if (!existsSync(pkgPath)) {
        console.error("❌ resources/app/package.json missing. Extraction incomplete.");
        exit(1);
    }

    const pkg  = JSON.parse(readFileSync(pkgPath, "utf-8"));
    const main = pkg.main || "index.js";
    const mainPath = join(appDir, main);

    if (!existsSync(mainPath)) {
        console.error(`❌ Discord main entry not found: ${mainPath}`);
        exit(1);
    }

    const REQUIRE_LINE = 'require("./sycord-hook.js");';
    let mainSrc = readFileSync(mainPath, "utf-8");

    if (mainSrc.includes(REQUIRE_LINE)) {
        console.log("… Discord entry already patched (idempotent)");
    } else {
        mainSrc = `// Sycord injection marker — safe to delete this line to disable\n${REQUIRE_LINE}\n${mainSrc}`;
        writeFileSync(mainPath, mainSrc);
        console.log(`… patched entry: ${main}`);
    }

    // ── Verify ──────────────────────────────────────────────────────────────
    const verifyMain = readFileSync(mainPath, "utf-8");
    const verifyHook = existsSync(join(appDir, "sycord-hook.js"));
    const asarGone   = !existsSync(appAsar);

    if (!verifyMain.includes(REQUIRE_LINE) || !verifyHook || !asarGone) {
        console.error("❌ Verification failed. State:");
        console.error(`   entry patched: ${verifyMain.includes(REQUIRE_LINE)}`);
        console.error(`   hook present:  ${verifyHook}`);
        console.error(`   app.asar gone: ${asarGone}`);
        exit(1);
    }

    console.log("");
    console.log("✅ Sycord injected successfully");
    console.log(`   Resources:  ${resourcesPath}`);
    console.log(`   App folder: ${appDir}`);
    console.log(`   Entry:      ${main}`);
    console.log(`   Hook:       ${join(appDir, "sycord-hook.js")}`);
    console.log(`   Source:     ${sycordDist}`);
    console.log("");
    console.log("   Launch Discord now. Watch the terminal for '[Sycord] Hook active 🔥'.");
    console.log("   To remove: node scripts/inject.mjs --uninject");
}

main();